services:
  - type: web
    name: whatsapp-sender
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: META_VERIFY_TOKEN
        sync: false
      - key: META_ACCESS_TOKEN
        sync: false
      - key: META_PHONE_NUMBER_ID
        sync: false
      - key: META_APP_ID
        sync: false
      - key: META_CONFIG_ID
        sync: false
      - key: PRIVATE_KEY_PASSWORD
        sync: false
      - key: FIREBASE_CREDENTIALS
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.0